- name: Configuration de apache
  hosts: localhost

  tasks:
    - name: Installation de apache2
      apt:
        name: apache2
        state: present

    - name: Lire la liste des domaines
      command: cat ./domaines.txt
      register: domaines

    - name: Convertire domaines fichier en ligne par ligne
      set_fact:
        domainesliste: "{{ domaines.stdout_lines }}"

    - name: Codage des sites availaibles
      copy:
        content: |
          "<VirtualHost *:80>

            ServerName {{ item }}
            DocumentRoot /var/www/{{ item }}

            <Directory /var/www/{{ item }}>
              AllowOverride All
              Require all granted
            </Directory>
          </VirtualHost>"
        dest: "/etc/apache2/sites-available/{{ item }}.conf"
      with_items: "{{ domainesliste }}"
      become: yes

    - name: Supprimer les liens symboliques site enable
      file:
        path: "/etc/apache2/sites-enabled/{{ item }}"
        state: absent
        force: yes
      with_items: "{{ domainesliste }}"
      ignore_errors: yes

    - name: Creation des liens symboliques site enable
      command: "sudo ln -s /etc/apache2/sites-available/{{ item }} /etc/apache2/sites-enabled/"
      with_items: "{{ domainesliste }}"
      become: yes

    - name: Creation des dossiers pour contenir les pages web
      file:
        path: "/var/www/{{ item }}"
        state: directory
      with_items: "{{ domainesliste }}"

    - name: Ajouter des pages disponible par defaut
      copy:
        content: |
          "<!DOCTYPE html>
           <html lang='en'>
           <head>
               <meta charset='UTF-8'>
               <meta http-equiv='X-UA-Compatible' content='IE=edge'>
               <meta name='viewport' content='width=device-width, initial-scale=1.0'>
               <title>Default</title>
           </head>
           <body>
               Bienvenue sur {{ item }}
           </body>
           </html>"
        dest: "/var/www/{{ item }}/index.html"
      with_items: "{{ domainesliste }}"
      become: yes

    - name: Restart apache
      service:
        name: apache2
        state: restarted